---
development:
  dialect: postgres
  database: docker_development
  user: docker
  password: docker
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://docker:docker@127.0.0.1:5432/docker_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://docker:docker@127.0.0.1:5432/docker_production?sslmode=disable"}}
